name: "CI Deep"

on:
  schedule:
    - cron: "0 1 * * 6" # at 1:00am UTC every Saturday
  workflow_dispatch:
    inputs:
      integrationFuzzRuns:
        default: "100000"
        description: "Integration: number of fuzz runs."
        required: false
      forkFuzzRuns:
        default: "1000"
        description: "Fork: number of fuzz runs."
        required: false

jobs:
  lint:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-lint.yml@main"

  build:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-build.yml@main"

  test-integration:
    needs: ["lint", "build"]
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@main"
    with:
      foundry-fuzz-runs: ${{ fromJSON(inputs.integrationFuzzRuns || '100000') }}
      foundry-profile: "test-optimized"
      match-path: "test/integration/**/*.sol"
      name: "Integration tests"

  test-fork:
    needs: ["lint", "build"]
    secrets:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@main"
    with:
      foundry-fuzz-runs: ${{ fromJSON(inputs.forkFuzzRuns || '1000') }}
      foundry-profile: "test-optimized"
      match-path: "test/fork/**/*.sol"
      name: "Fork tests"
