name: "CI Fork and Util tests"

on:
    schedule:
      - cron: "0 3 * * 1,3,5" # at 3:00 AM UTC on Monday, Wednesday and Friday

jobs:
  lint:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-lint.yml@main"

  build:
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-build.yml@main"

  test-fork:
      needs: ["lint", "build"]
      secrets:
        MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@main"
      with:
        foundry-profile: "test-optimized"
        match-path: "test/fork/**/*.sol"
        name: "Fork tests"

  test-utils:
    needs: ["lint", "build"]
    uses: "sablier-labs/reusable-workflows/.github/workflows/forge-test.yml@main"
    with:
      foundry-profile: "test-optimized"
      match-path: "test/utils/**/*.sol"
      name: "Utils tests"
