name: CI

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"
          token: ${{ secrets.CI_TOKEN }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build the contracts
        run: |
          forge --version
          forge build --sizes

      - name: "Cache the build so that it can be re-used by the other jobs"
        uses: "actions/cache/save@v3"
        with:
          path: "out"
          key: "foundry-build-${{ github.sha }}"

      - name: "Store contract ABIs as artifacts in GitHub Actions"
        uses: "actions/upload-artifact@v3"
        with:
          name: contract-abis
          path: |
            out/SablierV2ProxyTarget.sol/SablierV2ProxyTarget.json
            out/ISablierV2ProxyTarget.sol/ISablierV2ProxyTarget.json
            out/DataTypes.sol/CreateLinear.json
            out/DataTypes.sol/CreatePro.json
            out/Errors.sol/Errors.json
            out/Helpers.sol/Helpers.json

      - name: Run tests
        run: forge test

      - name: Add test summary
        run: |
          echo ## Tests >> $GITHUB_STEP_SUMMARY
          echo ✅ Passed >> $GITHUB_STEP_SUMMARY
