name: "Deploy Archive"

env:
  API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      admin:
        default: "0x0E109f35926575FC64Ec73735101966d434Ed591"
        description: "Contract admin. Defaults to 0x0E10...d591"
        required: false
      chain:
        default: "goerli"
        description: 'Chain name. Defaults to "goerli" if unspecified'
        required: false

jobs:
  deploy-archive:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"
          token: ${{ secrets.CI_TOKEN }}

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the SablierV2Archive contract"
        run: >-
          forge script script/DeployArchive.s.sol
          --broadcast
          --rpc-url "${{ inputs.chain }}"
          --sig "run(address)"
          -vvvv
          "${{ inputs.admin }}"

      - name: "Add summary"
        run: |
          echo "## Deployment result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
