name: "Deploy Proxy Target"

env:
  API_KEY_ETHERSCAN: ${{ secrets.API_KEY_ETHERSCAN }}
  API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
  FOUNDRY_PROFILE: "optimized"
  MNEMONIC: ${{ secrets.MNEMONIC }}
  RPC_URL_GOERLI: ${{ secrets.RPC_URL_GOERLI }}

on:
  workflow_dispatch:
    inputs:
      chain:
        default: "goerli"
        description: "Chain name as defined in the Foundry config."
        required: false
      permit2:
        default: "0x000000000022d473030f116ddee9f6b43ac78ba3"
        description: "The permit2 address."
        required: false

jobs:
  deploy-proxy-target:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"
          token: ${{ secrets.CI_TOKEN }}

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the SablierV2ProxyTarget contract"
        run: >-
          forge script script/DeployProxyTarget.s.sol
          --broadcast
          --rpc-url "${{ inputs.chain }}"
          --sig "run(address)"
          -vvvv
          "${{ inputs.permit2 }}"

      - name: "Add workflow summary"
        run: |
          echo "## Result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Done" >> $GITHUB_STEP_SUMMARY
