name: "List Address"

env:
  API_KEY_INFURA: ${{ secrets.API_KEY_INFURA }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    inputs:
      archive:
        description: 'The address of the archive contract.'
        required: true
        
      address:
        description: 'The address to list on the archive contract.'
        required: true

      chain:
        default: "goerli"
        description: 'Chain name. Defaults to "goerli" if unspecified'
        required: false

jobs:
  deploy-archive:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"
          token: ${{ secrets.CI_TOKEN }}

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "List an address on the archive contract"
        run: >-
          forge script script/ListAddressOnArchive.s.sol
          --broadcast
          --rpc-url "${{ inputs.chain }}"
          --sig "run(address,address)"
          -vvvv
          "${{ inputs.archive }}",
          "${{ inputs.address }}"
          
      - name: "Add summary"
        run: |
          echo "## Deployment result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
