name: "Close stale issues and PRs"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 6" # at 1:00am UTC every Saturday

jobs:
  stale:
    uses: "sablier-labs/reusable-workflows/.github/workflows/stale.yml@main"
